### ISSUE TITLE
Fix bug with spaces in user names

### ISSUE THREAD

**Issue by poppynorthing** [qubist/scrabblebag#34]

**Comment by qubist** [comment]
Names with multiple spaces
* Have weird IDs with spaces in them >:(
* Don't show as having multiple spaces in the name

To fix:
1) Fix bug with IDs :)
2) Fix using: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by qubist** [comment]
Closed by PR #40
