### ISSUE TITLE
UI Overhaul

### ISSUE THREAD

**Issue by poppynorthing** [qubist/scrabblebag#35]
![61834311869__7A5AC643-D2C3-41AE-A803-69F0E2496184](https://user-images.githubusercontent.com/69227755/89447471-dcaa1400-d70a-11ea-9421-d84bb8db1ebe.jpeg)

**Comment by poppynorthing** [comment]
![IMG_8786](https://user-images.githubusercontent.com/69227755/89448287-3c54ef00-d70c-11ea-8a5f-997e1b995369.jpeg)

includes mobile version

**Comment by qubist** [comment]
- [x] different hover vs active colors on buttons

**Comment by poppynorthing** [comment]
Potential Bag Images

![potential_pouch1](https://user-images.githubusercontent.com/69227755/89834358-8c222480-db17-11ea-97f8-221462367b45.png)
![johnny-automatic-leather-pouch](https://user-images.githubusercontent.com/69227755/89834361-8debe800-db17-11ea-9d34-1228d75b6c39.png)

**Comment by qubist** [comment]
- [x] edit mask to cover up cord and beads and stuff
